config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'reviews/new'
  get 'appointments/new'

  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/users/:id/calendar', to: 'users#calendar', as: 'calendar'

  resources :articles, only: [:index]
   
  resources :users, only: [:show] do
    resources :conversations, only: [:new, :create]
  end

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  resources :events, only: [:index, :show, :new, :create, :update, :destroy]
  get '/events/:id/status_change', to: 'events#status_change', as: 'status_change'

  resources :hospitals, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :appointments, only: [:new, :create]
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :replies, only: :destroy
  resources :posts, only: :show do
    resources :replies, only: :create
  end
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  skip_before_action :authenticate_user!, only: :index
  
  def index
    @articles = policy_scope(Article).all
  end
end

app/views/articles/index.html.erb
<div class="container py-5 mb-5">
  <div class="container ">
    <div class="justify-content-center">
      <ul class="nav nav-pills nav-fill toogle-bar">
        <li class="nav-item">
          <%= link_to "Hospitals", hospitals_path, class:"nav-link", style:"color:#8064A2;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Articles", articles_index_path, class:"nav-link active btn btn-primary", style:"background-color:;" %>
        </li>
      </ul>
    </div>

    <div class="container mt-5">
      <% @articles.each do |article| %>
        <div class= "card rounded-3 p-3">
          <div class="">
            <img id="article-img" class="rounded-3" src=<%= article.image %> alt="Article Picture">
          </div>
          <div class="p-3">
            <h1><%= article.title %></h1>
            <div class="card-border py-3">
              <p><%= article.content %></p>
              <a target="_blank" href="<%= article.link %>">Read more</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>