config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'reviews/new'
  get 'appointments/new'

  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/users/:id/calendar', to: 'users#calendar', as: 'calendar'

  resources :articles, only: [:index]
   
  resources :users, only: [:show] do
    resources :conversations, only: [:new, :create]
  end

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  resources :events, only: [:index, :show, :new, :create, :update, :destroy]
  get '/events/:id/status_change', to: 'events#status_change', as: 'status_change'

  resources :hospitals, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :appointments, only: [:new, :create]
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :replies, only: :destroy
  resources :posts, only: :show do
    resources :replies, only: :create
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :appointments
  has_many :attendants
  has_many :events
  has_many :events_as_attendant, through: :events, source: :attendants
  has_many :posts
  has_many :replies
  has_many :reviews
  has_many :conversations
  has_many :messages
  validates :username, presence: true
  validates :due_date, presence: true
  has_one_attached :avatar_cl
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_profile

  def show
    authorize @profile
    weeks_until_birth
    current_week
    week_info = YAML.load_file(Rails.root.join('config', 'week_info.yml'))
    # raise
    if weeks_until_birth.zero?
      info = week_info['default']
      @size = info['size']
      @length = info['length']
      @weight = info['weight']
      @image = info['image']
      @symptoms = info['symptoms']
      @baby_info = info['baby_info']
      @next_appointment = info['next_appointment']
    elsif week_info.key?(@current_week)
      info = week_info[@current_week]
      @size = info['size']
      @length = info['length']
      @weight = info['weight']
      @image = info['image']
      @symptoms = info['symptoms']
      @baby_info = info['baby_info']
      @next_appointment = info['next_appointment']
      # Week number not found in week_info hash
    end
    @articles = Article.all
    @article = @articles.sample
    @events = Event.all
    @event = @events.sample
  end

  def calendar
    authorize @profile

    if params[:date]
      date = params[:date]
    else
      date = Date.today.strftime("%Y-%m-%d")
    end
    # @current_day_appointments = Appointment.where(user: current_user, date: date)
    @appointments = Appointment.where(user: current_user)
    @current_day_events = Event.where(user: current_user, date: date)
    @events = Event.where(user: current_user)
    @attending = Event.joins(:attendants).where('attendants.user_id' => current_user.id, 'attendants.status' => 1)
    # @attending = Attendant.where(current_user.attendants.status == "attending", event != current_user) 
    @events_attending_not_created = current_user.attendants.select { |a| a.event.user != current_user && a.status == "attending" }
    # @events_attending_not_created_today =  @events_attending_not_created.select { |a| a.event.date == date}
    # year = Date.parse(date).year       WILL NEED THIS FOR EVENTS
    # month = Date.parse(date).month
    unless current_user.appointments.empty?
      @hospitals = current_user.appointments.map do |appointment|
        appointment.hospital
      end.uniq
    end
  end

  def weeks_until_birth
    @weeks = ((@profile.due_date - Date.today) / 7).to_i
  end

  def current_week
    @current_week = (40 - (weeks_until_birth))
  end

  private

  def set_profile
     @profile = current_user
  end
end
# if week_info.key == @weeks
  #

# NEED LATER
# link for the google calendar
# <a href="http://www.google.com/calendar/event?action=TEMPLATE&text=[event-title]&dates=[start-custom format='Ymd\\THi00\\Z']/[end-custom format='Ymd\\THi00\\Z']&details=[description]&location=[location]&trp=false&sprop=&sprop=name:" target="_blank" rel="nofollow">Add to my calendar</a>


#
# https://support.google.com/calendar/answer/41207?hl=en&ref_topic=10510447&sjid=16995394533718824250-AP

app/views/users/calendar.html.erb
<div class="my-2 py-3">
  <%= @events_attending %>
  <%= month_calendar do |date| %>
    <div type="button" class="myBtn" data-bs-toggle="modal" data-bs-target="#exampleModal<%=date%>">
      <%#= link_to calendar_path(current_user, date: date) do %>
        <!-- Modal -->
        <div class="modal fade" id="exampleModal<%=date%>" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header" style="background-color:#EAD6DE;">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Appointments and Events</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
              </div>
        
              <div class="modal-body">
                <% @current_day_appointments = @appointments.where(date: date).to_a %>
                <% @current_day_events = @events.where(date: date).to_a %>
                <% @events_attending = @attending.where(date: date).to_a %>
                <% @events_attending_not_created_today =  @events_attending_not_created.select { |a| a.event.date == date} %>
                <h2><%= date %></h2>
                <% if @current_day_appointments.empty? && @current_day_events.empty? && @events_attending.empty? %>
                  <h4>No appointments or events to display!</h4>
                <% else %>
                  <% unless @current_day_appointments.empty? %>
                    <div>
                      <h2>Private Appointments </h2>
                    </div>
                    <div>
                      <% @current_day_appointments.each do |appointment| %>
                        <div class="card-container">
                          <div class="card">
                            <div>
                              <h3><%= appointment.hospital.name %></h3>
                            </div>
                            <div style="display:flex;">
                              <h5><i class="fa-solid fa-location-dot"></i>
                               <%= appointment.hospital.address %></h5>
                            </div>
                            <div>
                              <h3><%= appointment.title %></h3>
                            </div>
                            <div>
                              <h5>Purpose: <%= appointment.purpose %></h5>
                            </div>
                            <div>
                              <p> <%= appointment.date.strftime('%B %d') %> at <%= appointment.time.strftime('%H:%M') %> </p>
                            </div>
                            <% if appointment.notes != "" %>
                              <div>
                                <p><%= appointment.notes %></p>
                              </div>
                            <% else %>
                              <div> </div>
                            <% end %>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                  <% unless @current_day_events.empty? && @events_attending.empty? %>
                    <div>
                      <h2>Events</h2>
                    </div>
                    <div>
                      <% @current_day_events.each do |event| %>
                        <div class="card-container">
                          <div class="card">
                            <div>
                              <h3><%= event.title %></h3>
                            </div>
                            <div>
                              <h5>Description: <%= event.content %></h5>
                            </div>
                            <div>
                              <p><i class="fa-solid fa-location-dot"></i> <%= event.location %></p>
                            </div>
                            <div>
                             <p> <%= event.date.strftime('%B %d') %> at <%= event.time.strftime('%H:%M') %> </p>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    </div>
                  <% end %>
                <% @events_attending_not_created_today =  @events_attending_not_created.select { |a| a.event.date == date} %>
                <% if @events_attending_not_created_today.any? %>
                  <% @events_attending_not_created_today.each do |attend| %>
                    <div class="card-container">
                      <div class="card">
                        <div>
                          <h3> <%= attend.event.title %> </h3>
                        </div>
                        <div>
                          <h5>Description: <%= attend.event.content %></h5>
                        </div>
                        <div>
                          <p><i class="fa-solid fa-location-dot"></i> <%= attend.event.location %></p>
                        </div>
                        <div>
                          <p> <%= attend.event.date.strftime('%B %d') %> at <%= attend.event.time.strftime('%H:%M') %> </p>
                        </div>
                      </div>
                    </div>
                  <% end %>
                <% end %>
                <% end %>
              </div>
              <%# <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div> %>
            </div>
          </div>
        </div>
        <p class="px-2" id="date"><%= date.day%></p>
        <% @appointments.each do |appointment| %>
          <% if appointment.date == date %>
            <i class="fa-solid fa-circle fa-2xs" style="color: #dd3647;"></i>
          <% end %>
        <% end %>
        <% @events.each do |event| %>
          <% if event.date == date %>
            <i class="fa-solid fa-circle fa-2xs" style="color: #33BBC5;"></i>
          <% end %>
        <% end %>
        <% if @events_attending_not_created.any? %>
          <% @events_attending_not_created_today.each do |attend| %>
            <% if attend.event.date == date %>
              <i class="fa-solid fa-circle fa-2xs" style="color: #dd99ff;"></i>
            <% end %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
  
  <% if @hospitals %>
    <div class="new_appt">
      <h4>Add new appointment:</h4>
      <div class="btn-group">
        <button type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
          Your Hospitals
        </button>
        <ul class="dropdown-menu" style="width:190px;">
          <% @hospitals.each do |hospital| %>
            <li><%= link_to hospital.name, new_hospital_appointment_path(hospital) %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<%# destroy_user_session_path, method: :delete %>
<div style="margin:10px">
  <div class="my-3 d-flex flex-column align-items-center">
    <h1><%= current_user.username %></h1>
    <% if current_user.avatar_cl.attached? %>
        <%= cl_image_tag(current_user.avatar_cl.key, width: "100", height: "100", class: "rounded-circle shadow") %>
    <% end %>
    <div class="container ">
      <div class="card align-items-center bg-cards">
        <% if @weeks.zero?%>
          <h4>Your baby will be arriving soon!</h4>
        <% elsif @weeks < 0 %>
          <h4>Congratulations on your baby!</h4>
        <% else %>
          <h4>You are on week: <span style="color:#301934;"><%= @current_week %>!</span></h4>
          <% @weeks == 1 ? week_display = "#{@weeks} week" : week_display = "#{@weeks} weeks" %>
          <h4>Only <%= week_display %> left!</h4>
        <% end %>
      </div>
    </div>
    <div class="container">
      <div class="card align-items-center">
        <% if @baby_info.nil?%>
          <h4>You are now a new parent!</h4>
          <center><h4>Make sure you rest whenever you can</h4></center>
        <% else %>
          <h3>This week your baby is:</h3>
          <h4><%= @baby_info %></h4>
          <h4> The size of <%= @size %>!</h4>
        <% end %>
        <%= image_tag @image, class: "card rounded-circle shadow", height: 200, width: 200 %>
      </div>
    </div>
    <% if !@next_appointment.nil? %>
      <div class="container">
        <div class="card align-items-center">
          <center>
            <h3>Around this time you should be booking:</h3>
            <h4><%= @next_appointment %></h4>
          </center>
        </div>
      </div>
    <% end %>
    <div class="container">
      <div class="card align-items-center">
        <% if @length.nil?%>
          <center>
              <h4>You just seek help whenever you need it</h4>
              <h4>Try going on short walks or other non-strenuous activities</h4>
              <h4>Eat healthy meals for you and you new baby!</h4>
          </center>
        <% else %>
          <h3>A little more information!</h3>
          <div>
            <center>
              <h4>Baby's current length is <%= @length %></h4>
              <h4>Baby's current weight is <%= @weight %></h4>
            </center>
          </div>
        <% end %>
        <% if !@symptoms.nil? %>
          <h4>This week you may feel:</h4>
          <div class="align-items-left" >
            <ul>
              <% @symptoms.each do |symptom| %>
                <li style="list-style-type: none;"><h4><%=symptom%></h4></li>
              <% end %>
            </ul>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <!-- mx-4 card p-0   -->

  <div class="container">
    <div class="accordion container" id="accordionExample">
      <div class="rounded shadow accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="collapsed accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
            Recommended Article for you
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse " aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <div class="my-3 px-2">
              <img id="article-img" class="rounded-3" src=<%= @article.image %> alt="Article Picture">
            </div>
            <div class="px-3">
              <h3><%= @article.title %></h3>
              <p><%= @article.content %></p>
              <a target="_blank" href="<%= @article.link %>">Read more</a>
            </div>
          </div>
        </div>
      </div>
      <div class="rounded shadow accordion-item my-4">
        <h2 class="accordion-header" id="headingTwo">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            Recommended Event for you
          </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <div>
              <%= cl_image_tag @event.photo.key, class: "shadow rounded-3  my-3 px-2", style:"width:100%; height:200px;" %>
            </div>
            <div class="card-container">
              <h3><%= @event.title %>: <%= @event.content %></h3>
              <p>Hosted by: <%= @event.user.username %></p>
              <p>
                <i class="fa-solid fa-calendar-days"></i>
                <%= @event.date.strftime('%B %d') %> at <%= @event.time.strftime('%H:%M') %> JST
              </p>
              <p>
                <i class="fa-solid fa-circle-check"></i>
                <% attending = @event.attendants %>
                <% all = attending.count + 1 %>
                <%= all %>
              </p>
              <p class = "d-flex justify-content-center">
                <%= link_to "See more", event_path(id: @event.id), class: "btn btn-primary" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>