config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'reviews/new'
  get 'appointments/new'

  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/users/:id/calendar', to: 'users#calendar', as: 'calendar'

  resources :articles, only: [:index]
   
  resources :users, only: [:show] do
    resources :conversations, only: [:new, :create]
  end

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  resources :events, only: [:index, :show, :new, :create, :update, :destroy]
  get '/events/:id/status_change', to: 'events#status_change', as: 'status_change'

  resources :hospitals, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :appointments, only: [:new, :create]
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :replies, only: :destroy
  resources :posts, only: :show do
    resources :replies, only: :create
  end
end

app/views/shared/_banner.html.erb
 <%# if request.path == "/" %> 
  <%# <h1>TokyoGlow</h1> %>
<%# elsif request.path.include? "hospitals" %>
  <%# <h1>Hospitals</h1> %>
<%# elsif request.path.include? "posts" %>
  <%# <h1>Posts</h1> %>
<%# elsif request.path.include? "calendar" %>
  <%# <h1><%= current_user.username`s calendar</h1>  %>
<%# elsif request.path.include? "user" %> 
  <%# <h1>Profile</h1> %>
<%# elsif request.path.include? "event" %> 
  <%# <h1>Events</h1> %>
<%# end %>

<div class="d-flex banner justify-content-center position-relative">
  <% if request.path == "/" %> 
    <div class="py-3"> 
      <h1>TokyoGlow</h1>
    </div>
  <% else %>
    <div class="back-arrow">
      <%= link_to 'javascript:history.back()' do %>
        <i class="fa-solid fa-chevron-left fa-2xl" style="color: #004444;"></i>
      <% end %>
    </div>
    <div class="d-flex py-3">
      <% if request.path.include? "calendar" %>
        <h1><%= current_user.username %>`s calendar</h1>
      <% elsif request.path.include? "user" %> 
        <h1>Profile</h1>
      <% elsif request.path.include? "conversations/" %>
        <div class="d-flex gap-3">
          <% if current_user == @conversation.user_to %>
            <% if @conversation.user_from.avatar_cl.attached? %>
              <%= cl_image_tag(@conversation.user_from.avatar_cl.key, width: "40", height: "40", radius: "max", background: "white") %>
            <% elsif @conversation.user_from.avatar %>
              <%= image_tag(@conversation.user_from.avatar, width: "40", height: "40") %>
            <% else %>
              <%= image_tag("userF1.png", width: "40", height: "40") %>
            <% end %>
              <h1><%= @conversation.user_from.username %></h1>
          <% else %>
            <% if @conversation.user_to.avatar_cl.attached? %>
              <%= cl_image_tag(@conversation.user_to.avatar_cl.key, width: "40", height: "40", radius: "max", background: "white") %>
            <% elsif @conversation.user_to.avatar %>
              <%= image_tag(@conversation.user_to.avatar, width: "40", height: "40") %>
            <% else %>
              <%= image_tag("userF1.png", width: "40", height: "40") %>
            <% end %>
            <h1><%= @conversation.user_to.username %></h1>
          <% end %>
        </div>
      <% else %>
        <h1><%= request.path.split(/\W+/)[1].to_s.capitalize %></h1>
      <% end %>
    </div>
  <% end %>
  <% if user_signed_in? %>
      <div class="log-out">
        <%= button_to destroy_user_session_path, data: {turbo_confirm: "Are you sure?"}, method: :delete, class: "logout-icon"  do %>
          <i class="fa-solid fa-right-from-bracket fa-2xl" style="color: #004444;"></i>
        <% end %>
      </div>
  <% end %>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="d-flex justify-content-around ">
  <% if user_signed_in? %>
    <%# event %>
    <%= link_to events_path do %>
        <div class="icon-flex">
          <i class="fa-solid fa-cake-candles fa-xl icon-wrapper" style="color: #004444;"></i>
        </div>
    <% end %>
    <%# chat/posts %>
    <%= link_to posts_path do %>
      <div class="icon-flex">
        <i class="fa-solid fa-comment fa-xl icon-wrapper" style="color: #004444; item-allign:center;"></i>
      </div>
    <% end %>
    <%# Profile %>
    <%= link_to user_path(:id) do %>
      <div class="icon-flex">
        <i class="fa-solid fa-user fa-xl icon-wrapper" style="color: #004444;"></i>
      </div>
    <% end %>
    <%# hospitals %>
    <%= link_to hospitals_path do %>
      <div class="icon-flex">
        <i class="fa-solid fa-hospital fa-lg icon-wrapper" style="color: #004444;"></i>
      </div>
    <% end %>
    <%# calendar %>
    <%= link_to calendar_path(:id) do %>
      <div class="icon-flex">
        <i class="fa-solid fa-calendar-days fa-xl icon-wrapper" style="color: #004444;"></i>
      </div>
    <% end %>

  <% else %>
    <%# chat/posts %>
    <%= link_to posts_path do %>
      <div class="icon-flex">
        <i class="fa-solid fa-comment fa-xl icon-wrapper" style="color: #004444;"></i>
      </div>
    <% end %>
    <%# home %>
    <%= link_to root_path do %>
      <div class="icon-flex">
        <i class="fa-solid fa-house fa-xl icon-wrapper" style="color: #004444;"></i>
      </div>
    <% end %>
    <%# hospitals %>
    <%= link_to hospitals_path do %>
      <div class="icon-flex">
        <i class="fa-solid fa-hospital fa-lg icon-wrapper" style="color: #004444;"></i>
      </div>
    <% end %>

  <% end %>
</div>