config/routes.rb
Rails.application.routes.draw do
  get 'articles/index'
  get 'reviews/new'
  get 'appointments/new'

  devise_for :users
  root to: "pages#home"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/users/:id/calendar', to: 'users#calendar', as: 'calendar'

  resources :articles, only: [:index]
   
  resources :users, only: [:show] do
    resources :conversations, only: [:new, :create]
  end

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create]
  end

  resources :events, only: [:index, :show, :new, :create, :update, :destroy]
  get '/events/:id/status_change', to: 'events#status_change', as: 'status_change'

  resources :hospitals, only: [:index, :show] do
    resources :reviews, only: [:create]
    resources :appointments, only: [:new, :create]
  end
  resources :posts, only: [:index, :new, :create, :destroy]
  resources :replies, only: :destroy
  resources :posts, only: :show do
    resources :replies, only: :create
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :replies, dependent: :destroy

  validates :title, :category, :content, presence: true

  include PgSearch::Model

  pg_search_scope :general_search,
    against: [ :content, :title, :category ],
    associated_against: {
      user: [ :username ]
    },
    using: {
      tsearch: { prefix: true }
  }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @posts = policy_scope(Post).all.order(created_at: :desc)
    if params[:query].present?
      @posts = Post.general_search(params[:query])
    end
  end

  def show
    @post = Post.find(params[:id])
    authorize @post
    @reply = Reply.new
    @conversation = Conversation.new
  end

  def new
    @post = Post.new
    authorize @post
  end

  def create
    # @post = Post.new(post_params)
    # @post.user = current_user
    # @post.save!
    @post = current_user.posts.create(post_params)
    @post.user = current_user
    authorize @post
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    authorize @post
    redirect_to posts_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :category)
  end
end

app/views/posts/index.html.erb
<div class="container py-5 mb-5">
  <div class="row justify-content-center">
    <div class="col-sm-8 mx-2">
      <ul class="nav nav-pills nav-fill toogle-bar">
        <li class="nav-item">
          <%= link_to "Public", posts_path, class:"nav-link active btn btn-primary", style:"background-color:;" %>
        </li>
        <li class="nav-item">
          <%= link_to "Private", conversations_path, class:"nav-link", style:"color:#8064A2;" %>
        </li>
      </ul>

      <div class="col-sm-8 my-3">
        <%= form_with url: posts_path, method: :get, class: "d-flex", html: { autocomplete: "off" }  do %>
          <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Search for categories, keywords..."
            %>
          <%= submit_tag "Search", name: "", class: "btn btn-success" %>
        <% end %>
      </div>
    </div>
  </div>

  <div class = "d-flex justify-content-center py-3">
    <%= link_to "Add a new post", new_post_path, class: "btn-main" %>
  </div>
  <hr/>


  <div>
    <% @posts.each do |post| %>
      <div class= "card rounded-3 p-2">
        <div class="d-flex gap-3 position-relative">
          <% if post.user.avatar_cl.attached? %>
            <%= cl_image_tag(post.user.avatar_cl.key, width: "50", height: "50", radius: "max", background: "white") %>
          <% elsif post.user.avatar %>
            <%= image_tag(post.user.avatar, width: "50", height: "50") %>
          <% else %>
            <%= image_tag("userF1.png", width: "50", height: "50") %>
          <% end %>
          <div class="d-flex flex-column justify-content-center">
            <h3><strong><%= post.user == current_user ? "You" : post.user.username %></strong></h3>
            <p><i><%= post.created_at.strftime("%a %b %e at %l:%M %p") %></i></p>
          </div>
          <% if policy(post).destroy? %>
            <%= button_to post, form: { data: { turbo_confirm: 'Are you sure?' } } , method: :delete, class: "delete-icon" do %>
              <i class="fa-solid fa-trash fa-xl" style="color: #004444;"></i>
            <% end %>
          <% end %>
        </div>
        <%= link_to post_path(post) do %>
          <h3 class = "py-1"><%= post.title %></h3>
          <hr/>
          <p>Category: <%= post.category %></p>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="container my-5">
  
  <div class="card p-3 rounded-3">
    <h1 class="text-center">Write your Post</h1>
    <%= simple_form_for(@post) do |f| %>
    <%= f.input :title %>
    <%= f.input :content %>
    <%= f.input :category, collection: ["General", "Food and Nutrition", "First Child", "Medical", "Event", "Recommendations", "Playdates"], selected: f.object.category || '1' %>
      <div class= "d-flex justify-content-center p-3">
        <%= f.submit "Submit your post", class: "btn-main" %>
      </div>
    <% end %>
    </div>
  </div>

</div>

app/views/posts/show.html.erb
<div class="container ">
  <div class= "">
    <div class="post-reply-container">

      <%# POST %>

      <div class="card p-3 ">
        <div class="d-flex gap-3 position-relative">
          <% if @post.user.avatar_cl.attached? %>
            <%= cl_image_tag(@post.user.avatar_cl.key, width: "60", height: "60") %>
          <% elsif @post.user.avatar %>
            <%= image_tag(@post.user.avatar, width: "60", height: "60") %>
          <% else %>
            <%= image_tag("userF1.png", width: "60", height: "60") %>
          <% end %>
          <div class="d-flex flex-column justify-content-center">
            <h3><strong><%= @post.user == current_user ? "You" : @post.user.username %></strong></h3>
            <p><i><%= @post.created_at.strftime("%a %b %e at %l:%M %p") %></i></p>
          </div>
          <% unless @post.user == current_user %>
            <%=  render "conversations/new", user: @post.user, conversation: @conversation%>
          <% end %>
          <% if policy(@post).destroy? %>
            <%= button_to @post, form: { data: { turbo_confirm: 'Are you sure?' } } , method: :delete, class: "delete-icon" do %>
              <i class="fa-solid fa-trash fa-xl" style="color: #004444;"></i>
            <% end %>
          <% end %>
        </div>
        <hr/>
        <h1 class= "text-center"><%= @post.title %></h1>
        <div class="post">
          <p><%= @post.content %></p>
        </div>
      </div>

      <%# REPLIES %>

       <%# .order(created_at: :desc) %>

      <div class="mb-5">
        <% @post.replies.each do |reply| %>
          <div class="card rounded-3 p-3 review-card ">
            <div class="d-flex gap-3 position-relative">
              <% if reply.user.avatar_cl.attached? %>
                <%= cl_image_tag(reply.user.avatar_cl.key, width: "40", height: "40") %>
              <% elsif reply.user.avatar %>
                <%= image_tag(reply.user.avatar, width: "40", height: "40") %>
              <% else %>
                <%= image_tag("userF1.png", width: "40", height: "40") %>
              <% end %>
              <div class="d-flex flex-column justify-content-center">
                <h4><strong><%= reply.user == current_user ? "You" : reply.user.username %></strong></h4>
                <p><%= reply.created_at.strftime("%a %b %e at %l:%M %p") %></p>
              </div>
              <% unless reply.user == current_user %>
                <%=  render "conversations/new", user: reply.user, conversation: @conversation%>
              <% end %>
              <% if policy(reply).destroy? %>
                <%= button_to reply, form: { data: { turbo_confirm: 'Are you sure?' } } , method: :delete, class: "delete-icon" do %>
                  <i class="fa-solid fa-trash fa-lg" style="color: #004444;"></i>
                <% end %>
              <% end %>
            </div>
            <hr/>
            <div class="reply">
              <p><%= reply.content %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <%# MESSAGE FORM %>

    <div class= "container position-relative">
      <%= simple_form_for [@post, @reply], html: {class: ""} do |f| %>
        <%= f.input :content,
          label: false,
         placeholder: "Reply to #{@post.user == current_user ? "your" : "#{@post.user.username}'s"} post",
          wrapper_html: {class: "flex-grow-1"}
       %>
        <button type="submit" class="send-icon"><i class="fa-solid fa-paper-plane fa-xl" style="color: #004444;"></i></button>
      <% end %>
    </div>

  </div>
</div>